export const data = [{
    id: '1',
    name: 'Netflix',
    price: '20',
    color: '#EF5350',
    desc: 'This is the description',
    billPeriod: '1',
    billUnit: 'Month',
    firstPayment: '20',
    paymentMethod: 'Credit Card',
    note: 'This is the note',
    prices: {
        priceDay: "0.66",
        priceMonth: "20.00",
        priceWeek: "5.00",
        priceYear: "240.00",
    },
},
{
    id: '2',
    name: 'Spotify',
    price: '5',
    color: '#66BB6A',
    desc: 'This is the description',
    billPeriod: '1',
    billUnit: 'Month',
    firstPayment: '20',
    paymentMethod: 'Credit Card',
    note: 'This is the note',
    prices: {
        priceDay: "0.16",
        priceMonth: "5.00",
        priceWeek: "1.25",
        priceYear: "60.00",
    },
},
{
    id: '3',
    name: 'Amazon',
    price: '10',
    color: '#FFCA28',
    desc: 'This is the description',
    billPeriod: '1',
    billUnit: 'Month',
    firstPayment: '20',
    paymentMethod: 'Credit Card',
    note: 'This is the note',
    prices: {
        priceDay: "0.33",
        priceMonth: "10.00",
        priceWeek: "2.50",
        priceYear: "120.00",
    },
},
{
    id: '4',
    name: 'Google',
    price: '25',
    color: '#9FA8DA',
    desc: 'This is the description',
    billPeriod: '1',
    billUnit: 'Month',
    firstPayment: '20',
    paymentMethod: 'Credit Card',
    note: 'This is the note',
    prices: {
        priceDay: "0.83",
        priceMonth: "25.00",
        priceWeek: "6.25",
        priceYear: "300.00",
    },
},
{
    id: '5',
    name: 'Tinder',
    price: '50',
    color: '#F48FB1',
    desc: 'This is the description',
    billPeriod: '1',
    billUnit: 'Month',
    firstPayment: '20',
    paymentMethod: 'Credit Card',
    note: 'This is the note',
    prices: {
        priceDay: "1.66",
        priceMonth: "50.00",
        priceWeek: "23.50",
        priceYear: "600.00",
    },
},
];